install.packages("spatstat")
install.packages("tidyverse")
install.packages("shiny")
install.packages("countrycode")
install.packages("reshape2")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages("leaflet")
install.packages("ggforce")
install.packages("ape")
install.packages("tidytree")
install.packages("here")
install.packages("plotly")
install.packages("gridExtra")
install.packages("cowplot")
install.packages("ips")
install.packages("BiocManager")
BiocManager::install("ggtree")
install.packages("ips")
# source("https://bioconductor.org/biocLite.R")
# biocLite("BiocInstaller")
# BiocInstaller::biocLite(c("ggtree", "treeio"))
# install.packages("BiocManager")
# library(BiocManager)
# install.packages("ggtree")
# install.packages("treeio")